apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-1
  description: |
    A service for testing Backstage functionality. Configured for
    GitHub Actions.
  annotations:
      backstage.io/techdocs-ref: url:https://github.com/imsurajkr/backstage-temp/tree/main
spec:
  type: service
  owner: DevOps-Team
  lifecycle: production
